In [26]:
import sklearn
import sklearn.datasets
import seaborn as sns
import numpy as np

# Create a function to generate a subset of points on a line, with added \pm 2 noise
def generateRandomLinearSet(size, width, slope, yInt):
    def round(x): return float("{0:.2f}".format(x))
    
    outputArray = []
    for x in range(size):
        inValue = round(np.random.random_sample() * width)
        outValue = round(inValue * width + yInt + np.random.normal())
        outputArray.append([inValue,outValue])
    return outputArray

# Create the array we shall train on.
linearArray = np.array(generateRandomLinearSet(100,10,5,5))

In [6]:
# Seperate all of the x-values of the array into an array with shape (n,1)
xTrain = np.reshape(linearArray[:,0],(100, 1))

# Refer to prior; substitute y-values
yTrain = np.reshape(linearArray[:,1],(100, 1))

print(xTrain)
print(yTrain)

[[9.36]
 [1.42]
 [5.86]
 [3.71]
 [4.01]
 [8.78]
 [8.24]
 [8.16]
 [7.32]
 [3.06]
 [6.44]
 [5.3 ]
 [2.24]
 [1.67]
 [7.56]
 [1.3 ]
 [6.98]
 [4.6 ]
 [9.96]
 [7.67]
 [3.65]
 [9.5 ]
 [4.7 ]
 [5.35]
 [2.96]
 [6.63]
 [7.09]
 [7.  ]
 [0.19]
 [9.15]
 [1.28]
 [1.47]
 [6.82]
 [7.58]
 [5.67]
 [0.45]
 [7.11]
 [4.42]
 [6.22]
 [5.95]
 [9.16]
 [9.39]
 [3.85]
 [5.16]
 [5.22]
 [6.56]
 [6.29]
 [4.8 ]
 [9.13]
 [3.27]
 [9.87]
 [3.98]
 [4.87]
 [3.  ]
 [4.03]
 [3.66]
 [7.06]
 [7.6 ]
 [6.04]
 [2.35]
 [2.34]
 [4.48]
 [8.45]
 [0.14]
 [4.65]
 [0.35]
 [3.32]
 [4.26]
 [3.56]
 [0.23]
 [9.6 ]
 [9.57]
 [0.66]
 [4.92]
 [8.54]
 [5.22]
 [4.58]
 [0.04]
 [7.39]
 [6.63]
 [7.38]
 [0.54]
 [6.12]
 [3.64]
 [0.54]
 [1.29]
 [2.73]
 [9.46]
 [2.62]
 [6.28]
 [9.67]
 [4.51]
 [3.66]
 [6.97]
 [7.43]
 [5.92]
 [8.42]
 [3.47]
 [5.71]
 [6.39]]
[[100.13]
 [ 18.45]
 [ 63.18]
 [ 42.15]
 [ 45.14]
 [ 92.02]
 [ 90.14]
 [ 85.08]
 [ 78.58]
 [ 34.2 ]
 [ 68.8 ]
 [ 58.31]
 [ 28.1 ]
 [ 22.23]
 [ 80.25]
 [ 17.81]
 [ 75.82]
 [ 49.96]
 [104.45]
 [ 80.23]

In [7]:
# Define the MyLinear object
myLinear = sklearn.linear_model.LinearRegression()

# Train the object to our training set
myLinear.fit(xTrain,yTrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [8]:
# Print the array the machine expects for the set we trained it on.
myLinear.predict(xTrain)

array([[ 98.36178878],
       [ 19.33916265],
       [ 63.52813746],
       [ 42.13032308],
       [ 45.11606462],
       [ 92.58935513],
       [ 87.21502036],
       [ 86.41882261],
       [ 78.0587463 ],
       [ 35.66121641],
       [ 69.30057111],
       [ 57.95475325],
       [ 27.50018953],
       [ 21.8272806 ],
       [ 80.44733953],
       [ 18.14486603],
       [ 74.67490588],
       [ 50.98802299],
       [104.33327186],
       [ 81.54211143],
       [ 41.53317477],
       [ 99.75513483],
       [ 51.98327017],
       [ 58.45237684],
       [ 34.66596923],
       [ 71.19154075],
       [ 75.76967778],
       [ 74.87395532],
       [  7.09762233],
       [ 96.2717697 ],
       [ 17.9458166 ],
       [ 19.83678624],
       [ 73.0825104 ],
       [ 80.64638897],
       [ 61.63716782],
       [  9.685265  ],
       [ 75.96872722],
       [ 49.19657806],
       [ 67.11102731],
       [ 64.42385993],
       [ 96.37129442],
       [ 98.66036293],
       [ 43.52366913],
       [ 56

In [9]:
# We "score" the program, on the training sets.
myLinear.score(xTrain,yTrain)

0.998763848072069

In [11]:
# Create a new set to test the machine on
testArray = np.array(generateRandomLinearSet(100,10,5,5))

# Split into x and y arrays
xTest = np.reshape(testArray[:,0],(100, 1))
yTest = np.reshape(testArray[:,1],(100, 1))

# Score our machine on the test sets; much more realistic estimate of the accuracy
myLinear.score(xTest,yTest)

[[ 88.42]
 [ 68.99]
 [ 20.55]
 [ 99.83]
 [ 59.09]
 [ 18.46]
 [ 78.82]
 [  5.97]
 [ 78.05]
 [ 17.85]
 [ 25.98]
 [ 74.97]
 [ 70.83]
 [ 15.48]
 [ 91.1 ]
 [103.1 ]
 [ 81.16]
 [ 67.59]
 [ 77.14]
 [ 10.6 ]
 [ 30.27]
 [100.45]
 [ 30.92]
 [ 50.11]
 [ 95.4 ]
 [ 99.33]
 [ 16.17]
 [ 96.82]
 [ 40.41]
 [ 16.17]
 [  4.64]
 [ 70.13]
 [ 79.25]
 [ 37.09]
 [ 96.36]
 [ 85.83]
 [ 24.88]
 [ 14.81]
 [ 67.2 ]
 [ 60.04]
 [ 53.22]
 [ 41.03]
 [ 62.02]
 [ 22.38]
 [ 20.76]
 [ 11.02]
 [ 97.18]
 [ 81.56]
 [ 22.61]
 [ 67.92]
 [ 21.94]
 [ 68.56]
 [  6.79]
 [ 45.72]
 [ 38.31]
 [ 25.11]
 [ 66.62]
 [ 87.9 ]
 [ 49.44]
 [ 12.93]
 [ 74.15]
 [ 76.44]
 [ 75.32]
 [ 35.76]
 [100.03]
 [ 35.19]
 [ 83.95]
 [101.3 ]
 [ 71.88]
 [ 15.32]
 [104.43]
 [ 32.21]
 [ 39.99]
 [ 32.65]
 [ 44.29]
 [ 51.25]
 [ 96.36]
 [ 46.89]
 [ 62.52]
 [ 12.06]
 [ 92.73]
 [ 44.96]
 [ 93.43]
 [ 31.72]
 [ 65.48]
 [ 23.41]
 [ 79.65]
 [ 58.86]
 [ 98.27]
 [ 85.61]
 [103.64]
 [ 45.45]
 [ 64.72]
 [ 36.55]
 [ 18.43]
 [ 75.36]
 [ 98.37]
 [ 93.55]
 [ 48.17]
 [ 50.46]]

0.9990475191065512

In [12]:
# Predicts what yTest would be for given xTest; for user enjoyment
myLinear.predict(xTest)

array([[ 89.90218775],
       [ 68.50437337],
       [ 22.72300306],
       [ 99.75513483],
       [ 58.85047571],
       [ 19.93631096],
       [ 78.35732045],
       [  5.50522684],
       [ 77.56112271],
       [ 18.34391547],
       [ 26.10684348],
       [ 74.97348004],
       [ 69.99724414],
       [ 15.15912449],
       [ 92.19125626],
       [102.04420335],
       [ 80.34781481],
       [ 67.6086509 ],
       [ 76.46635081],
       [ 11.3771852 ],
       [ 30.48593107],
       [100.35228314],
       [ 30.48593107],
       [ 48.79847919],
       [ 94.57984949],
       [ 99.15798653],
       [ 16.45294582],
       [ 96.86891801],
       [ 39.24410626],
       [ 16.95056941],
       [  6.4009493 ],
       [ 71.19154075],
       [ 80.54686425],
       [ 36.95503774],
       [ 97.86416519],
       [ 86.51834733],
       [ 24.21587383],
       [ 15.45769864],
       [ 64.62290936],
       [ 59.64667346],
       [ 51.88374545],
       [ 41.1350759 ],
       [ 61.73669254],
       [ 21

In [43]:
# Begin California Housing portion
myData = sklearn.datasets.fetch_california_housing()

trainingX = myData.data[:15480]
testX = myData.data[15480:]

trainingY = myData.target[:15480]
testY = myData.target[15480:]

myLinear.fit(trainingX,trainingY)

myLinear.score(testX, testY)

myLinear.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'normalize': False}